/*
 * Auto-generated by Frida. Please modify to match the signature of SecKeyRawSign.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
    onEnter(log, args, state) {
        log(`SecKeyRawSign()=${args[2].readCString()}=`);
        log('SecKeyRawSign called from:\n' +
            Thread.backtrace(this.context, Backtracer.ACCURATE)
                .map(DebugSymbol.fromAddress).join('\n') + '\n');
    },

    onLeave(log, retval, state) {
    }
});
