/*
 * Auto-generated by Frida. Please modify to match the signature of -[Foundation.__NSSwiftData initWithBase64EncodedString:options:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
    onEnter(log, args, state) {
        this.arg2 = args[2];
    },

    onLeave(log, retval, state) {
        var before = new ObjC.Object(this.arg2);
        var after = ObjC.classes.NSString.alloc().initWithData_encoding_(retval, 4);
        // log(`-[NSData initWithBase64EncodedString:]before=${before}=`);
        log(`-[NSData initWithBase64EncodedString:]after=${after}=`);
    }
});
