services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/home/vscode/app:cached
      - venv:/home/vscode/app/.venv
    ports:
      - 9080:9080
    tty: true
    stdin_open: true

  theos:
    build:
      context: ./theos
      dockerfile: Dockerfile
    volumes:
      - ../:/home/vscode/app:cached
    tty: true
    stdin_open: true

volumes:
  venv:
    driver: local
