/*
 * Auto-generated by Frida. Please modify to match the signature of -[NSData initWithBase64EncodedData:options:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
    onEnter(log, args, state) {
        this.arg2 = args[2];
    },

    onLeave(log, retval, state) {
        var before = ObjC.classes.NSString.alloc().initWithData_encoding_(this.arg2, 4);
        // var after = ObjC.classes.NSString.alloc().initWithData_encoding_(retval, 4);
        log(`-[NSData initWithBase64EncodedData:]before=${before}=`);
        // log(`-[NSData initWithBase64EncodedData:]after=${after}=`);
    }
});
